### ISSUE TITLE
Pocket computers instantly crash game upon GUI opening

### ISSUE THREAD

**Issue by BinaryBurgr** [mystiacraft/cc-tweaked-fabric#11]
## Useful information to include:
 - Minecraft: 1.14.4
 - Fabric Loader: 0.6.2+build.166
 - Fabric API: 0.4.0+build.240
 - CC: Tweaked: 1.83.2+build.7
 - Detailed reproduction steps: Got another one for you. :-) Both regular and advanced pocket computers instantly crash the game when I right click to open their GUI. This happens with and without OptiFine.

<details>
<summary>Expand for full crash report</summary>

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/1/19 8:30 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at dan200.computercraft.client.gui.GuiComputer.method_2389(GuiComputer.java:102)
	at net.minecraft.class_465.render(class_465.java:83)
	at dan200.computercraft.client.gui.GuiComputer.render(GuiComputer.java:142)
	at net.minecraft.class_757.method_3192(class_757.java:686)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dan200.computercraft.client.gui.GuiComputer.method_2389(GuiComputer.java:102)
	at net.minecraft.class_465.render(class_465.java:83)
	at dan200.computercraft.client.gui.GuiComputer.render(GuiComputer.java:142)

-- Screen render details --
Details:
	Screen name: dan200.computercraft.client.gui.GuiPocketComputer
	Mouse location: Scaled: (320, 180). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['BinaryBurgr'/277, l='MpServer', x=157.19, y=64.00, z=-50.43]]
	Chunk stats: Client Chunk Cache: 841, 575
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 16 - climatic, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (129,63,-75), Chunk: (at 1,3,5 in 8,-5; contains blocks 128,0,-80 to 143,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 6362 game time, 6362 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:421)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5668197816 bytes (5405 MB) / 8305246208 bytes (7920 MB) up to 8305246208 bytes (7920 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx8192m
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.3
		adorn: Adorn 1.4.2+1.14.4
		amethystmod: Amethyst Mod 1.2.0
		anvil_fix: AnvilFix 1.1.2
		appleskin: AppleSkin 1.0.7
		aquarius: Aquarius 1.3.1+1.14.1
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		autofish: Autofish 0.8.4
		beachslimes: Beach Slimes 1.3.0+mc1.14.4
		beaconflight: BeaconFlight 1.1.0
		bettersleeping: Better Sleeping 0.2.1
		betterthanmending: BetterThanMending 1.0.0
		biom4st3rpokeballs: Biom4st3rPokeballs 1.3
		block_booster: Block Booster 0.0.1
		blockmeter: Block Meter 1.1.3
		blue_endless_jankson: jankson 1.1.2
		brokenxp: Broken XP 1.0.3
		cardinal-components-base: Cardinal Components API 2.0.1
		cardinal-components-entity: Cardinal Components API 2.0.1
		cloth: Cloth Events 0.6.0
		cloth-config: Cloth Config 0.2.4+build.17
		cloth-config2: Cloth Config v2 1.2.1
		clothesline-fabric: Clothesline 0.1.2
		clothesline_motor: Tumble Dryer 1.1
		composableautomation: Composable Automation 0.6.0+mc1.14.4
		computercraft: CC:T for Fabric 1.83.2+build.7
		couplings: Couplings 1.2.0
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.0
		cursedchests: CursedChests 2.3.24
		cwt: Climatic World Type 1.1.3
		darkelevators: Elevators 1.1.3
		ding: Ding 2.0.3
		dynamicfps: Dynamic FPS 1.0.2
		easyexcavate: Easy Excavate 1.5.1
		enchxchg: Enchantments Exchanger 1.14.4-fabric-1.0.5
		everythingisahat: Everything is a Hat 1.0.3
		extra-pressure-plates: Extra Pressure Plates 1.1.2
		fabric: Fabric API 0.4.0+build.240-1.14
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-furnaces: Fabric Furnaces 1.1.7
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.50+build.1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabriccontrolling: Fabric Controlling 1.0.1
		fabricloader: Fabric Loader 0.6.2+build.166
		faeriefire: Faerie Fire 1.0.1
		fatxporbs: Fat Experience Orbs 0.0.6
		fiber2cloth: Fiber To Cloth 1.2.0
		fmagnet: Fabric Magnet ${version}
		foamfix: FoamFix 0.12.1
		glassdoor: Glass Doors 1.3.2
		harvest: Harvest 1.0.4
		healthoverlay: Health Overlay 2.2.10
		iamverysmart: I Am Very Smart 1.5.0+mc1.14.4
		infinityfix: Infinity Fix 1.1.0
		inventorysorter: Inventory Sorter 1.5.7
		itemscroller: Item Scroller 0.15.0-dev.20190720.190250
		jankson: Jankson 1.0.0+j1.1.2
		jargm: Just Another Redstone Gate Mod 1.0.1
		leadvillagers: Lead Villagers 1.2.0+mc1.14.4
		leaf-decay: Leaf Decay 1.1.0
		libblockattributes_core: LibBlockAttributes (Core) 0.4.9
		libblockattributes_items: LibBlockAttributes (Items) 0.4.9
		libcd: LibCapableData 1.3.1+1.14.4
		libgui: LibGui 1.3.2
		malilib: MaLiLib 0.10.0-dev.20
		me_zeroeightsix_fiber: fiber 0.7.0-4
		minecraft: Minecraft 1.14.4
		minihud: MiniHUD 0.19.0-dev.20190825.170729
		ml3lib: ML3 Library 1.0.0
		modmenu: Mod Menu 1.7.11+build.121
		modnametooltip: Mod Name Tool Tips 1.1.1
		nbtcrafting: NBT Crafting 1.2.4+1.14.4
		nicetohave: Nice to Have 1.2.0
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.50
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.0
		pathsuggestion: Path Suggestion 0.2.0
		recipemod: Recipe Mod 1.0.0
		redstonetweaks: Redstone Tweaks 1.0.2
		right-click-clear: Right Click Clear 1.1.0
		riptide_fix: Riptide Fix 1.1.0
		roughlyenoughitems: Roughly Enough Items 3.1.5+build.23
		roughlyenoughresources: Roughly Enough Resources 1.1.0
		rtp: Random Teleport Command 1.0.0
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		simpleteleporters: Simple Teleporters 2.1.0
		smartermending: Smarter Mending 1.1.0
		smokeextender: Smoke Extender 1.2.1
		smoothbedrock: Smooth Bedrock (Fabric) 1.1.4
		sodden: Sodden 1.0.1.2
		sonyikaarftl: Advanced Rotten Flesh to Leather 1.4.4
		soulbound: Soulbound 1.0.1
		soulshards: Soul Shards Respawn 1.0.11
		stockpile: Stockpile 1.0.9+1.14.4
		terraform: Terraform 1.1.8+build.15
		terrestria: Terrestria 1.0.11+build.40
		theoneprobe: The One Probe 1.4.29.beta
		tinyfuel: Tiny Fuel 0.1.0
		tramplestopper: Trample Stopper 1.14.4-1.2-universal
		trapexpansion: Trap Expansion 1.3.1
		traverse: Traverse 2.0.8+build.26
		trident_fixer: Trident Fixer 1.0.0
		trumpet-skeleton: Trumpet Skeleton 1.1.0
		tweakeroo: Tweakeroo 0.10.0-dev.20190903.193019
		vanilladeathchest: VanillaDeathChest ${version}
		variablepaxels: VariablePaxels 1.14.4-1.0.1
		voxelmap: VoxelMap 1.9.13
		wildworld: Wild World 1.1.2
		yabm: YABM 2.0.1
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

</details>

**Comment by svitoos** [comment]
Crash caused by [Inventory Sorter](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)

Workaround:

- Add "dan200.computercraft.client.gui.GuiComputer", "dan200.computercraft.client.gui.GuiPocketComputer" to the blacklist (config/inventorysorter/blacklist.json5).

- Or turn off the 'displaySort' option ("Display button in inventory").

**Comment by BinaryBurgr** [comment]
Confirmed, Inventory Sorter is the issue. Blacklisting those two GUIs works perfectly. Although, it is strange that Inventory Sorter sees those as sortable inventories in the first place. Not sure which mod is "at fault" here.
