### ISSUE TITLE
Crash on starting

### ISSUE THREAD

**Issue by rubenio1** [mystiacraft/cc-tweaked-fabric#12]
## Useful information to include:
 - Minecraft version: 1.14.4
 - CC: 1.83.2 Build 7
 - Just crashes when pressing play in the launcher, no other mods.
```

[Info: 2019-10-05 07:34:43.5474547: Process_Windows.cpp(128)] Read thread is 11824
[Info: 2019-10-05 07:34:43.5477075: ClientHandler.cpp(141)] Entering DoClose!
[Info: 2019-10-05 07:34:43.5477510: ClientHandler.cpp(143)] DoClose got past CEF_REQUIRE_UI_THREAD!
[Info: 2019-10-05 07:34:43.5477830: ClientHandler.cpp(174)] DoClose: known browser removed.
[Info: 2019-10-05 07:34:43.5478978: ClientHandler.cpp(184)] DoClose: main browser removed.
[Info: 2019-10-05 07:34:43.5584032: ClientHandler.cpp(196)] Entering OnBeforeClose!
[Info: 2019-10-05 07:34:43.5585046: ClientHandler.cpp(198)] OnBeforeClose got past CEF_REQUIRE_UI_THREAD!
[Info: 2019-10-05 07:34:44.0481828: ClientHandler.cpp(244)] Hiding launcher!
[Info: 2019-10-05 07:34:44.3619576: GameCallbacks.cpp(138)] Game/FabricLoader (main) Info Loading for game Minecraft 1.14.4
[Info: 2019-10-05 07:34:47.6867262: GameCallbacks.cpp(138)] Launcher/launcher (main) Info 

Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!

	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)

	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)

	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: computercraft requires {fabric @ [*]})

	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170)

	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)

	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)

	... 2 more

Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?

	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)

	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)

	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)

	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)

	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168)

	... 4 more


[Info: 2019-10-05 07:34:47.6867918: GameCallbacks.cpp(138)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code 1
[Info: 2019-10-05 07:34:47.6969883: GameController.cpp(321)] Game closed with id 4
[Info: 2019-10-05 07:34:47.6971796: NetQueue.cpp(534)] NetQueue: Starting net action http://hopper.minecraft.net/crashes/submit_report/
[Info: 2019-10-05 07:34:48.0505126: NetQueue.cpp(401)] NetQueue: Primary ip: 50.17.208.54, Url: hopper.minecraft.net
[Info: 2019-10-05 07:34:48.0505709: NetQueue.cpp(433)] NetQueue: Action failed with result "The requested URL returned error: 400 BAD REQUEST" (22) : http://hopper.minecraft.net/crashes/submit_report/
[Info: 2019-10-05 07:34:48.0505889: NetQueue.cpp(472)] NetQueue: Action finished: http://hopper.minecraft.net/crashes/submit_report/
[Info: 2019-10-05 07:34:48.0507089: ClientHandler.cpp(271)] Creating launcher window.
[Info: 2019-10-05 07:34:48.1067505: LauncherMain.cpp(88)] Running Launcher
[Info: 2019-10-05 07:34:48.1081455: NetQueue.cpp(202)] NetQueue: Setting up.
[Info: 2019-10-05 07:34:48.1082362: NetQueue.cpp(207)] NetQueue: Initiating shutdown.
[Info: 2019-10-05 07:34:48.1091960: LauncherMain.cpp(161)] Launcher core version: 2.1.5964 (2d12ae3b04458774a644a7bb7a3745a624f3ce46)
[Info: 2019-10-05 07:34:48.1092134: NetQueue.cpp(202)] NetQueue: Setting up.
[Info: 2019-10-05 07:34:48.1264548: LauncherAppRenderer.cpp(83)] Javascript bridge extended.
[Info: 2019-10-05 07:34:48.2996623: LauncherAppRenderer.cpp(217)] Creating renderer context...
[Info: 2019-10-05 07:34:49.6779919: NetQueue.cpp(534)] NetQueue: Starting net action https://launchermeta.mojang.com/v1/products/launcher/d03cf0cf95cce259fa9ea3ab54b65bd28bb0ae82/windows-x86.json
[Info: 2019-10-05 07:34:49.7118132: NetQueue.cpp(401)] NetQueue: Primary ip: 216.137.59.38, Url: launchermeta.mojang.com
[Info: 2019-10-05 07:34:49.7119478: NetQueue.cpp(472)] NetQueue: Action finished: https://launchermeta.mojang.com/v1/products/launcher/d03cf0cf95cce259fa9ea3ab54b65bd28bb0ae82/windows-x86.json


```

**Comment by svitoos** [comment]
CC:T depends on [fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api).

**Comment by rubenio1** [comment]
Thanks!
